name: Publish on Docker Hub
 
on:
  pull_request:
    branches:
      - 'main'
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PWD }}
      -
        name: Create image and push nop-scraper-service to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_LOGIN }}/${{ secrets.DOCKER_NAME }}:latest
          secrets: |
            "PAT=${{ secrets.PAT }}" 
