name: Deploy

on:
  pull_request:
    branches:
      - 'main'
      
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - run: |
        mkdir -P .ssh/authorized_keys2
        chmod 700 .ssh
        chmod 640 .ssh/authorized_keys2
        touch .ssh/authorized_keys2/id_rsa.pub
        echo ${{ secrets.DEPLOY_PUB_KEY }} >> .ssh/authorized_keys2/id_rsa.pub
    -
        name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            ls -al 
