name: Deploy

on:
  pull_request:
    branches:
      - 'main'
      
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    -   run: sudo cat /etc/ssh/sshd_config
    -   run: ls -l /etc/ssh/sshd_config
    -   run: sudo echo "CASignatureAlgorithms +ssh-rsa" >> /etc/ssh/sshd_config
    -
        name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            ls -al 
