name: Deploy

on:
  pull_request:
    branches:
      - 'main'
      
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - run: |
        sudo mkdir .ssh
        sudo chmod 700 .ssh
        sudo mkdir .ssh/authorized_keys
        sudo chmod 640 .ssh/authorized_keys 
        sudo touch .ssh/authorized_keys/id_rsa.pub
        sudo echo '${{ secrets.DEPLOY_PUB_KEY }}' >> .ssh/authorized_keys/id_rsa.pub
        sudo cat .ssh/authorized_keys/id_rsa.pub
        sudo /bin/su -c "echo 'CASignatureAlgorithms +ssh-rsa' >> /etc/ssh/sshd_config"
        sudo cat /etc/ssh/sshd_config
    -
        name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            ls -al 
