name: Deploy

on:
  pull_request:
    branches:
      - 'main'
      
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    -
        name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: 22
          script: |
              docker rm cr.yandex/${{ secrets.REGISTRY_ID }}/${{ secrets.DOCKER_NAME }}:latest
              docker rmi cr.yandex/${{ secrets.REGISTRY_ID }}/${{ secrets.DOCKER_NAME }}:latest
              docker system prune -f
              docker run cr.yandex/${{ secrets.REGISTRY_ID }}/${{ secrets.DOCKER_NAME }}:latest
