
name: Build

on: 
  workflow_dispatch:

jobs: 
  yc-cr-login-build-push:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v2
     # Login into Yandex CR
     - run: |
        ( cat | docker login --username json_key --password-stdin cr.yandex; ) <<EOF${{ secrets.YC_SA_JSON_CREDENTIALS }}EOF

     # Build Docker image
     - run: 
        docker build . --file .Dockerfile --tag cr.yandex/${{ secrets.YC_REGISTRY_ID }}/${{ secrets.DOCKER_NAME }}:latest
     
     # Push Docker image to yandex registry
     - run: docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/${{ secrets.DOCKER_NAME }}:latest
     
     # Logout of docker and sa-account at the same time 
     - run: docker logout 
