name: Yandex Cloud Tests

on: 
  workflow_dispatch:

jobs: 
  build-and-push-image:
    runs-on: ubuntu-latest
    
    steps:
     - run: echo "::add-mask::${{ secrets.YC_SA_JSON_CREDENTIALS }}" | docker login \ 
            --username json_key \
            --password-stdin \
            cr.yandex
     - run: docker logout
      
