name: Yandex Cloud Tests

on: 
  workflow_dispatch:

jobs: 
  login-into-yandex-cr:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v2
    # Login into Yandex CR
     - run: touch key.json
     - run: echo '${{ secrets.YC_SA_JSON_CREDENTIALS }}' >> key.json
     - run: cat key.json | docker login --username json_key --password-stdin cr.yandex

     # Build Docker image
     - run: docker build . --file .Dockerfile --tag cr.yandex/${{ secrets.YC_REGISTRY_ID }}/hello-world:${{ github.sha }}
     - run: docker images
     
     # Push Docker image to yandex registry
     - run: docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/hello-world:${{ github.sha }}
     
     # Logout of docker and sa-account at the same time 
     - run: docker logout      
